### PR TITLE
docs: add Chinese translation of Interpreter Pattern

### PR DESCRIPTION
**Pull request by autoload**
### Translate behavior design patterns into Chinese.
**Translation Content:**

- [x]  3 Behavior design patterns

    - [x] 3.1 Chain of responsibility
    - [x] 3.2. Command
    - [x] 3.3. Interpreter
    - [x] 3.4. Iterator
    - [x] 3.5. Mediator
    - [x] 3.6. Memento
    - [x] 3.7. Null Object
    - [x] 3.8. Observer
    - [x] 3.9. Specification
    - [x] 3.10. State
    - [x] 3.11. Strategy
    - [x] 3.12. Template Method
    - [x] 3.13. Visitor

### CODE REVIEW

**Comment by autoload** [comment]
docs: add Chinese translation of [Iterator, Mediator] Pattern

**Comment by autoload** [comment]
docs: add Chinese translation of Memento Pattern

**Comment by autoload** [comment]
docs: add Chinese translation of Null Object Pattern

**Comment by autoload** [comment]
docs: add Chinese translation of Observer Pattern

**Comment by autoload** [comment]
docs: add Chinese translation of Specification Pattern

**Comment by autoload** [comment]
docs: add Chinese translation of State Pattern

**Comment by autoload** [comment]
docs: add Chinese translation of Strategy Pattern

**Comment by autoload** [comment]
docs: add Chinese translation of Template Method Pattern

**Comment by autoload** [comment]
docs: add Chinese translation of Visitor Pattern

**Review by domnikl — APPROVED** [review]

**Comment by domnikl** [comment]
Thanks again @autoload!

**Pull request merged**
