### PR TITLE
Creational :: added missing return types & minor refactor

### PR DESCRIPTION
**Pull request by atakde**

### CODE REVIEW

**Comment by atakde** [comment]
@domnikl Can you please review it?

**Review by domnikl — CHANGES_REQUESTED** [review]
I like your changes very much! Could you please fix the minor coding style issue so I can get it merged?

**Comment by atakde** [comment]
@domnikl Thanks for the review. I sent a lint commit for fixing the coding style issue.

**Review by domnikl — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
