### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by didacusAbella**
added italian translation. Happy to contribute!

### CODE REVIEW

**Comment by domnikl** [comment]
Thanks for the translation. It'll take a while to review it, so bear with me please.

**Review by domnikl — CHANGES_REQUESTED** [review]
Could you please also add a link in the repos README for it? I will then create it at RTD after merging it in.

**Comment by didacusAbella** [comment]
link added

**Review by domnikl — APPROVED** [review]

**Comment by domnikl** [comment]
Thanks @didacusAbella! It's now available on RTD at https://designpatternsphp.readthedocs.io/it/latest/README.html

**Pull request merged**
