### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by thetechnicalchallenge**

### CODE REVIEW

**Comment by thetechnicalchallenge** [comment]
I am not very familiar with CI but I would say that this construction failure is not mine.

**Comment by thetechnicalchallenge** [comment]
@domnikl @piotrgradzinski 
If anyone has time to do a review this week, that would be great.

**Comment by domnikl** [comment]
Merged main in, CI is working again.

**Comment by domnikl** [comment]
Merged it in and set up RTD to build it and linked it to the main project. The translation is now ready at https://designpatternsphp.readthedocs.io/fr/latest/README.html Merci beaucoup!

**Pull request merged**
