### PR TITLE
Add pattern Interpreter

### PR DESCRIPTION
**Pull request by a1812**

### CODE REVIEW

**Comment by a1812** [comment]
Hi @domnikl please check my PR

**Comment by domnikl** [comment]
Hi @a1812 and first of all, thanks for your PR! There's also a Specification pattern in the repo and I know, Interpreter is a GoF pattern. They both seem very similar, maybe Specification is just the wrong name for it and we should rename it? Would be very interested in your opinion here, what do you think?

**Comment by a1812** [comment]
Hi, this diagram should clarify this pattern (GoF interpreter), perhaps better than auto-diagram earlier from PhpStorm.
I believe that binary logic is the best demonstration to apply visually the GoF interpreter
image

**Comment by a1812** [comment]
maybe I answered vaguely, but these are different patterns

**Comment by a1812** [comment]
ping @domnikl

**Review by domnikl — APPROVED** [review]

**Comment by domnikl** [comment]
Sorry @a1812 for letting you wait some time! Looks perfect, I'll merge it in. Thanks very much for your effort!

**Pull request merged**
